### ISSUE TITLE
make RTF and PRM accept non-self-contained files

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#484] opened 2017-10-20 11:28 UTC
As the title says.

1. I think it is sufficient to load the default cgenff rtf and prm, but maybe make it flexible.
2. Reading those are easy, but the main concern is to make self-contained files without spamming to many parameters into the files (filter out the irrelevant ones)
3. Minor concern: does it conflict later with a loaded cgenff rtf and prm?

**Comment by raimis** [comment] 2017-10-20 12:56
When we switch using *ParmEd*, it will be doable!

**Comment by j3mdamas** [comment] 2017-10-20 13:15
We should not wait for that. We need to fix it ASAP, right after 1.10.0 release.

**Comment by stefdoerr** [comment] 2018-03-27 13:42
Is this still an issue after we switched to parmed?

**Comment by raimis** [comment] 2018-03-27 16:15
Yes!

**Comment by stefdoerr** [comment] 2019-03-01 15:02
I'll ask again. Is this still an issue? I don't understand at all from the description what the issue is. Could you explain better at least?

**Comment by j3mdamas** [comment] 2019-03-01 15:24
The issue, as far as I remember, was that using some input RTF and PRM files for parameterize required them to be self-contained, i.e. have all the parameters inside them and not rely on general CHARMM FF parameter files. I guess it's importance depends on how much we want to support CHARMM on parameterize.

**Comment by stefdoerr** [comment] 2019-03-01 15:47
Let's make it a bit of a rule to open issues with test files. Otherwise we lose context and it's hard to reproduce. I will close this until it comes up again.

**Closed by stefdoerr** 2019-03-01 15:47 UTC
Labels: Topic: Parameterize, Type: Enhancement
