### ISSUE TITLE
parameterization.writers error (PRM file) KeyError: ('C261', 'C261x4')

### ISSUE THREAD

**Issue by MBenabderrahmane** [Acellera/htmd#776] opened 2018-09-24 07:50 UTC
Hi, I'm trying to use the parameterize module for my ligand and unfortunately I'm getting this error when the script try to write the final parameters 

== Writing results ==

2018-09-22 12:26:34,055 - htmd.parameterization.dihedral - INFO - Start parameter optimization
2018-09-22 12:26:34,055 - htmd.parameterization.dihedral - INFO - Initial RMSD: 5.099872 kcal/mol
2018-09-22 12:28:45,132 - htmd.parameterization.dihedral - INFO - Current RMSD: 0.515603 kcal/mol
2018-09-22 12:36:26,145 - htmd.parameterization.dihedral - INFO - Current RMSD: 0.490852 kcal/mol
2018-09-22 12:50:18,631 - htmd.parameterization.dihedral - INFO - Current RMSD: 0.407101 kcal/mol
2018-09-22 12:55:54,655 - htmd.parameterization.dihedral - INFO - Current RMSD: 0.257487 kcal/mol
2018-09-22 17:03:38,605 - htmd.parameterization.dihedral - INFO - Final RMSD: 0.257487 kcal/mol
2018-09-22 17:03:38,606 - htmd.parameterization.dihedral - INFO - Finished parameter optimization
2018-09-22 17:03:39,782 - htmd.parameterization.writers - INFO - Write MOL2 file: res/parameters/CGenFF_2b6/HF-6-31Gstar-vacuum/mol.mol2
2018-09-22 17:03:39,784 - htmd.parameterization.writers - INFO - Write PDB file: res/parameters/CGenFF_2b6/HF-6-31Gstar-vacuum/mol.pdb
2018-09-22 17:03:39,785 - htmd.parameterization.writers - INFO - Write COOR file: res/parameters/CGenFF_2b6/HF-6-31Gstar-vacuum/mol.coor
2018-09-22 17:03:39,787 - htmd.parameterization.writers - INFO - Write PSF file: res/parameters/CGenFF_2b6/HF-6-31Gstar-vacuum/mol.psf
2018-09-22 17:03:39,788 - htmd.parameterization.writers - INFO - Write RTF file: res/parameters/CGenFF_2b6/HF-6-31Gstar-vacuum/mol.rtf
Traceback (most recent call last):
  File "/home/med/.conda/envs/py35/bin/parameterize", line 11, in <module>
    sys.exit(main_parameterize())
  File "/home/med/.conda/envs/py35/lib/python3.5/site-packages/htmd/parameterization/cli.py", line 288, in main_parameterize
    writeParameters(mol, parameters, qm, method, netcharge, args.outdir, original_coords=orig_coor)
  File "/home/med/.conda/envs/py35/lib/python3.5/site-packages/htmd/parameterization/writers.py", line 307, in writeParameters
    writePRM(mol, parameters, file_)
  File "/home/med/.conda/envs/py35/lib/python3.5/site-packages/htmd/parameterization/writers.py", line 152, in writePRM
    val = parameters.bond_types[type]
KeyError: ('C261', 'C261x4')

Thanks for any suggestion on how to fix that bug. 

Best,
MB

**Comment by stefdoerr** [comment] 2018-09-24 08:43
Duplicate of https://github.com/Acellera/htmd/issues/754 ?
Could you share the input molecule so that we can debug it?
Thanks!

**Comment by MBenabderrahmane** [comment] 2018-09-24 08:47
@<TRIPOS>MOLECULE
mdg8fj.pdb
 55 59 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1  N3        -0.9440    4.0400    8.2180 N.ar    0  UNK0       -0.2537
      2  N4         1.1950    6.2540    2.9120 N.ar    0  UNK0       -0.2627
      3  N2         1.0020    2.8970   12.3540 N.ar    0  UNK0       -0.2540
      4  C4         0.1690    4.5570    6.1370 C.ar    0  UNK0        0.0023
      5  C5         0.2110    3.5150    8.7060 C.ar    0  UNK0        0.0796
      6  C6         0.0710    5.1550    4.7740 C.ar    0  UNK0        0.0017
      7  C7        -1.2340    2.0830   11.9070 C.ar    0  UNK0       -0.0238
      8  C8         1.3290    3.9690    6.6320 C.ar    0  UNK0       -0.0433
      9  H8         2.1020    3.9310    6.0810 H       0  UNK0        0.0631
     10  C9         5.0860    2.4500    8.5790 C.ar    0  UNK0       -0.0250
     11  C10        0.1070    3.0550   10.1210 C.ar    0  UNK0        0.0193
     12  C11       -0.9430    4.5400    6.9870 C.ar    0  UNK0        0.0360
     13  H11       -1.7540    4.9110    6.6610 H       0  UNK0        0.0836
     14  C12        1.3840    3.4290    7.9300 C.ar    0  UNK0        0.0016
     15  C13       -0.1500    2.3160   12.7740 C.ar    0  UNK0        0.0753
     16  C14        0.9200    1.2010   14.7480 C.ar    0  UNK0       -0.0497
     17  H14        1.6740    0.9890   14.2100 H       0  UNK0        0.0625
     18  C15        1.2000    5.6900    4.1270 C.ar    0  UNK0        0.0353
     19  H15        2.0300    5.6470    4.5870 H       0  UNK0        0.0836
     20  C16       -0.1630    1.9070   14.2040 C.ar    0  UNK0        0.0187
     21  C17        1.1120    3.2610   11.0770 C.ar    0  UNK0        0.0375
     22  H17        1.9170    3.6830   10.7990 H       0  UNK0        0.0836
     23  C18        2.5990    2.7670    8.4550 C.2     0  UNK0       -0.0520
     24  H18        2.4900    2.1080    9.1300 H       0  UNK0        0.0624
     25  N1        -1.2620    1.8870   16.3530 N.ar    0  UNK0       -0.2626
     26  C20       -1.0700    2.4470   10.5780 C.ar    0  UNK0       -0.0461
     27  H20       -1.7730    2.2800    9.9610 H       0  UNK0        0.0628
     28  C21       -1.2170    2.2290   15.0570 C.ar    0  UNK0        0.0367
     29  H21       -1.9480    2.7200   14.6990 H       0  UNK0        0.0836
     30  C22        3.8420    3.0380    8.0380 C.2     0  UNK0       -0.0540
     31  H22        3.9340    3.6640    7.3300 H       0  UNK0        0.0624
     32  C23       -1.1280    5.2440    4.0830 C.ar    0  UNK0       -0.0511
     33  H23       -1.9240    4.8910    4.4630 H       0  UNK0        0.0625
     34  C24        0.8780    0.8160   16.0750 C.ar    0  UNK0       -0.0430
     35  H24        1.5900    0.3190   16.4610 H       0  UNK0        0.0633
     36  C25        5.1520    1.7920    9.8220 C.ar    0  UNK0       -0.0546
     37  H25        4.3610    1.6860   10.3380 H       0  UNK0        0.0623
     38  C26        0.0160    6.3220    2.2870 C.ar    0  UNK0        0.0276
     39  H26       -0.0140    6.7120    1.4220 H       0  UNK0        0.0829
     40  C27        6.2770    2.5930    7.8560 C.ar    0  UNK0       -0.0546
     41  H27        6.2680    3.0520    7.0240 H       0  UNK0        0.0623
     42  C28       -2.5410    1.4520   12.3530 C.3     0  UNK0       -0.0377
     43  H28       -3.1240    2.1420   12.7330 H       0  UNK0        0.0278
     44  H28       -2.3580    0.7680   13.0320 H       0  UNK0        0.0278
     45  H28       -2.9830    1.0380   11.5830 H       0  UNK0        0.0278
     46  C29       -0.2260    1.1720   16.8260 C.ar    0  UNK0        0.0276
     47  H29       -0.2540    0.8930   17.7340 H       0  UNK0        0.0829
     48  C30        6.3600    1.2930   10.3090 C.ar    0  UNK0       -0.0612
     49  H30        6.3870    0.8570   11.1530 H       0  UNK0        0.0618
     50  C31        7.4660    2.0750    8.3350 C.ar    0  UNK0       -0.0612
     51  H31        8.2570    2.1600    7.8160 H       0  UNK0        0.0618
     52  C32       -1.1640    5.8520    2.8360 C.ar    0  UNK0       -0.0430
     53  H32       -1.9850    5.9440    2.3660 H       0  UNK0        0.0633
     54  C33        7.5200    1.4310    9.5690 C.ar    0  UNK0       -0.0617
     55  H33        8.3440    1.0900    9.8980 H       0  UNK0        0.0618
@<TRIPOS>BOND
     1    39    38    1
     2    38    52   ar
     3    38     2   ar
     4    53    52    1
     5    52    32   ar
     6     2    18   ar
     7    32    33    1
     8    32     6   ar
     9    18    19    1
    10    18     6   ar
    11     6     4    1
    12     9     8    1
    13     4     8   ar
    14     4    12   ar
    15     8    14   ar
    16    13    12    1
    17    12     1   ar
    18    41    40    1
    19    31    30    1
    20    51    50    1
    21    40    50   ar
    22    40    10   ar
    23    14    23    1
    24    14     5   ar
    25    30    23    2
    26    30    10    1
    27     1     5   ar
    28    50    54   ar
    29    23    24    1
    30    10    36   ar
    31     5    11    1
    32    54    55    1
    33    54    48   ar
    34    36    48   ar
    35    36    37    1
    36    27    26    1
    37    11    26   ar
    38    11    21   ar
    39    48    49    1
    40    26     7   ar
    41    22    21    1
    42    21     3   ar
    43    45    42    1
    44     7    42    1
    45     7    15   ar
    46    42    43    1
    47    42    44    1
    48     3    15   ar
    49    15    20    1
    50    20    16   ar
    51    20    28   ar
    52    17    16    1
    53    29    28    1
    54    16    34   ar
    55    28    25   ar
    56    34    35    1
    57    34    46   ar
    58    25    46   ar
    59    46    47    1

**Comment by stefdoerr** [comment] 2018-09-24 08:50
Today is a holiday here but I'll look into it as soon as I can this week :) Thanks!

**Comment by MBenabderrahmane** [comment] 2018-09-24 08:52
I'm using 1.13.4 HTMD/parameterize version
Thanks

**Comment by stefdoerr** [comment] 2018-09-25 10:37
Thanks a lot! I made a PR here https://github.com/Acellera/htmd/pull/777 that fixed it. Once it gets merged I'll inform you.

**Comment by stefdoerr** [comment] 2018-09-25 12:29
@MBenabderrahmane  this is fixed in the newest github version of HTMD. You can either use the github version or wait for the next HTMD release.

**Closed by stefdoerr** 2018-09-25 12:29 UTC
Labels: Type: Support

**Comment by MBenabderrahmane** [comment] 2018-09-25 12:58
@stefdoerr thanks a lot for the fix ^^ :)
