### ISSUE TITLE
Parameterize GAFF: non-bonded parameters missing

### ISSUE THREAD

**Issue by katkovs** [Acellera/htmd#197] opened 2016-11-30 09:39 UTC
Hello HTMD team,

Parameterization of certain molecules with GAFF produces the following message:

> Not writing Amber FRCMOD: Can't express unset 1-4 VdW terms in Amber file format

and no parameters are written out, only the plots of the dihedrals. Obviously it has to do something with the 1-4 interactions, my guess is that a dihedral involving a hydrogen atom type with VdW parameters equal to 0 causes the problem, but this is just a guess. Can I do something to circumvent this and get the frcmod file?

I'm sending the input mol2 file I use, the log file from the parameterize run, and this was the call:
parameterize -m L-lactate.mol2 -c -1 -n 4 -f GAFF -b 6-31g-star  --vacuum --qmcode Gaussian  > param.DFT.6-31g.vacuum.log

Thanks,
Kalina
[lactate.zip](https://github.com/Acellera/htmd/files/621420/lactate.zip)

**Comment by j3mdamas** [comment] 2016-11-30 10:19
I don't think there is. @mj-harvey?

**Comment by j3mdamas** [comment] 2016-11-30 11:51
Actually, I just ran:
```
parameterize -m L-lactate.mol2 -f GAFF --theory RHF -b 6-31g-star --vacuum --qmcode PSI4 -o param -c -1
```

But I'm in the repo version, while you are using the miniconda version (even though I don't know which one because you're probably using PYTHONPATH=/usr/users/katkovs/miniconda3/lib/python3.5/site-packages/htmd). Can you do: `cat /usr/users/katkovs/miniconda3/lib/python3.5/site-packages/htmd/version.py`? And if you're using the conda version, you don't need to set the PYTHONPATH.

I am going to update the level of theory, and try again. I won't be able to test Gaussian, but maybe the issue is solved in the repo version and you'll just have to wait for the next release.

João

**Comment by katkovs** [comment] 2016-11-30 15:03
Thanks for the quick reply! Yes, you are right, I had an older version. Now I cloned the latest one from here, and now parameterize runs to the end and writes the frcmod file. So, that issue is not there anymore.

There is another thing though: The nonbonded parameters for atomtype "zd" are not written, so tleap fails to create the prmtop file. Do you get the same thing? I attach the output files. 

Moreover, as in issue #198, there are more atomtypes in the frcmod file than in the mol2 file and I still can't figure out why. I understand that the htmd frcmod file has to be self-sufficient (as opposed to when using antechamber), but wouldn't it be even without these parameters? I mean, tleap will anyways only use the terms from the frcmod file that involve the atomtypes present in the mol2 file, right? Or am I missing something? In the end, this does not matter, if those terms are redundant. If they are necessary though, and they don't end in the prmtop, then this is a problem.

Thanks, 
Kalina
[new_lactate.zip](https://github.com/Acellera/htmd/files/622100/new_lactate.zip)

**Comment by mj-harvey** [comment] 2016-11-30 15:24
THis bug should already be fixed in the latest release. If not, it's certainly fixed in master already.

**Comment by mj-harvey** [comment] 2016-11-30 15:27
The extra GAFF parameters come from two sources: 1) the initial typing made with ambertools is made in such a way that the output files are stand-alone, containing all of the parameters required. Somethines this seems to produce files contianing more parameters than are actually used in the parameterisation
2) The parameterisation process may duplicate types during the fitting process so that dihedrals can be defined uniquely. You'll end up seeing several atomtypes with the same vdw parameters as a result.

Matt

**Comment by katkovs** [comment] 2016-11-30 15:46
Thanks for the reply, now it is clear. Brings peace of mind to know it is unnecessary or "duplicate" terms which can be safely ignored by the enduser.

**Comment by j3mdamas** [comment] 2016-11-30 16:01
so, can we update the remaining issue here? what is it exactly?

**Comment by katkovs** [comment] 2016-11-30 16:09
So, the frcmod is written out, but the nonbonded parameters of exactly one atomtype (zd) are missing. This prevents tleap from creating a topology file. 

All the other terms involving this atom type are present.

**Comment by j3mdamas** [comment] 2016-11-30 16:14
thanks. let me see.

**Comment by mj-harvey** [comment] 2016-11-30 17:45
@j3mdamas  probably incorrect use of a python "not"  if zd is the H type with 0 vdw parameters.

**Comment by j3mdamas** [comment] 2016-11-30 17:50
thanks for the tip

**Comment by katkovs** [comment] 2016-11-30 17:52
It is not the hydrogen, it is another atom type (carbon, atom name C2, original type probably c3).

**Comment by j3mdamas** [comment] 2016-11-30 17:55
yeah, it's a carbon.

**Comment by j3mdamas** [comment] 2016-12-01 14:49
So, @mj-harvey: the missing nonbonded parameter is already missing after the antechamber initial guess.

Plus, the antechamber already produces a `ANTECHAMBER.FRCMOD` file which has more info than the `.frcmod` file that comes out of `parmchk2`. Probably something to check out?

I will assign this issue to you, as per your request.

**Comment by j3mdamas** [comment] 2016-12-01 14:50
@katkovs, thanks for reporting this issue! We will try to get back at you as soon as possible

João

**Comment by mj-harvey** [comment] 2016-12-02 20:04
@katkovs fixed in commit 6002bd7920c353f8258e16014de5ea62f0b95eee

**Closed** 2016-12-02 20:04 UTC
Labels: Parameterize

**Comment by j3mdamas** [comment] 2016-12-02 20:06
Actually 8fdcd670b606fbc005534b5acf85f602adde3cfe. That one was tricky

**Comment by j3mdamas** [comment] 2016-12-02 20:07
@mj-harvey, did you check the `ANTECHAMBER.FRCMOD`?
