### ISSUE TITLE
Charmm build sets atoms outside the box

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#308] opened 2017-04-12 15:33 UTC
I tried to use the Charmm.build to make a build from a pdb file (attached, see smol.pdb). I ended up with structure.pdb, where some waters and ions are outside the box. What is going on here? I tried the build with the protein only, and still some waters and ions get placed outside the box.

```
topos  = ['top/top_all22star_prot.rtf', './params/parameters/CGenFF_2b6/b3lyp-cc-pVDZ-water/mol.rtf', 'top/top_water_ions.rtf']
params = ['par/par_all22star_prot.prm', './params/parameters/CGenFF_2b6/b3lyp-cc-pVDZ-water/mol.prm', 'par/par_water_ions.prm']

molbuilt = charmm.build(smol, topo=topos, param=params, outdir='./build/', saltconc=0.1)
```

[charmm_prob.zip](https://github.com/Acellera/htmd/files/917059/charmm_prob.zip)

**Comment by stefdoerr** [comment] 2017-04-12 15:36
I don't see any atoms outside the box in `smol.pdb`

![vmdscene](https://cloud.githubusercontent.com/assets/7935362/24966186/8f6e2b28-1fa6-11e7-8bb8-7d52adfb7e76.png)

**Comment by stefdoerr** [comment] 2017-04-12 15:38
Ah sorry you mean after building that file. Joao will take a look at it I guess since he assigned it to himself ;)

**Comment by j3mdamas** [comment] 2017-04-12 15:38
`structure.pdb` has

**Comment by j3mdamas** [comment] 2017-04-12 15:39
@piia600, can you share the script and inputs that you used to generate `smol`?

**Comment by piia600** [comment] 2017-04-12 17:09
Here are the files. 

[files.zip](https://github.com/Acellera/htmd/files/917322/files.zip)

**Comment by stefdoerr** [comment] 2017-04-21 17:50
```
htmd.builder.charmm - WARNING - Failed to set coordinates for 1 atoms.\n",
htmd.builder.charmm - WARNING - Failed to guess coordinates for 7 atoms due to bad angles.\n",
htmd.builder.charmm - WARNING - Poorly guessed coordinates for 74 atoms.\n",
htmd.builder.charmm - WARNING - Please check /storage/brno6/home/piia/dhla_fluorsub_charmm/build/log.txt for further information.\n",
```

Sorry I don't have access now to a computer with VMD to test it but the warnings indicate that psfgen had problems determining the atom type probably of some atom. Could you send me the log that is mentioned in the warning?

**Comment by j3mdamas** [comment] 2017-04-21 19:10
@piia600, can you also share the ligand parameters that were absent on the files.zip and are used in the build? Otherwise I can't reproduce your results and check what is going on.

**Comment by piia600** [comment] 2017-04-24 07:19
Here are the ligand parameters. I see now, that there are probably some problems in them, since the rtf should not have most values as zeroes... But anyway, I can reproduce the initial problem also with using only the protein pdb file, leaving off all the problems connected to the ligand. 

Here is the log file from only the protein, I think the problem might be in amber style residue names. 

[mol.zip](https://github.com/Acellera/htmd/files/950657/mol.zip)
[log.txt](https://github.com/Acellera/htmd/files/950664/log.txt)

**Comment by stefdoerr** [comment] 2017-04-24 08:00
I think the issue is this line:
```
smol.set('segid', 'W', sel='water')
```
The solvate function already takes care of putting waters in separate segments. When you force a new segment on them you have multiple residues with same resid in the same segment which causes errors in psfgen as can be seen in the `log.txt`

```
psfgen) ERROR: failed on residue TIP3 from pdb file
psfgen) duplicate residue key 677
```
Try removing that line

**Comment by piia600** [comment] 2017-04-24 08:12
Okay, thanks. I didn't know the water is treated differently in the segments, so based on the tutorials I assumed I have to make a segment for it.

**Comment by stefdoerr** [comment] 2017-04-24 08:17
Yeah it's not very clear in the tutorials. We might want to point it out
unless we find some nicer way of dealing with segments.

**Comment by j3mdamas** [comment] 2017-04-24 08:33
it's hard. we might lock in the segments from user modification after important functions have been called (like solvate), but that's a mess.

anyway, closing this issue.

**Closed by j3mdamas** 2017-04-24 08:33 UTC
Labels: help wanted
