### ISSUE TITLE
Bond information is lost when running parameterize

### ISSUE THREAD

**Issue by yiannisgaldadas** [Acellera/htmd#320] opened 2017-04-27 11:29 UTC
Hello HTMD team,

I tried to use the parametrize tool for a ligand parmeterization but when I run the following command:

> parameterize -m MLN.mol2 -c -1 -f GAFF2

I get the following messages
Unknown bond type for BOND(C2-N3:un), assuming it is a single bond
Unknown bond type for BOND(C10-O2:un), assuming it is a single bond
Unknown bond type for BOND(C1-C17:un), assuming it is a single bond

Along with several errors:

> Traceback (most recent call last):
  File "/home/yiannis/miniconda3/lib/python3.6/site-packages/htmd/parameterization/fftype.py", line 58, in __init__
    self._rtf = AmberRTF(mol, "mol.prepi", "mol.frcmod")
  File "/home/yiannis/miniconda3/lib/python3.6/site-packages/htmd/parameterization/ff.py", line 675, in __init__
    idx = self.index_by_name[ff[1]]
KeyError: 'H4'

> During handling of the above exception, another exception occurred:
 
> Traceback (most recent call last):
  File "/home/yiannis/miniconda3/bin/parameterize", line 6, in <module>
    sys.exit(htmd.parameterization.cli.main_parameterize())
  File "/home/yiannis/miniconda3/lib/python3.6/site-packages/htmd/parameterization/cli.py", line 175, in main_parameterize
    outdir=args.outdir)
  File "/home/yiannis/miniconda3/lib/python3.6/site-packages/htmd/parameterization/ffmolecule.py", line 101, in __init__
    fftype = FFType(self, method=self.method)
  File "/home/yiannis/miniconda3/lib/python3.6/site-packages/htmd/parameterization/fftype.py", line 64, in __init__
    raise RuntimeError("FFTyping failed running Antechamber and Parmchk2")
RuntimeError: FFTyping failed running Antechamber and Parmchk2

which lead to the termination of the whole procedure. Both antechamber and parmchk2 run without any issue, so I don't understand why FFTyping fails to run them.
Any ideas on why does this happen?

Best wishes,
Yiannis

**Comment by j3mdamas** [comment] 2017-04-27 11:33
Hi,

Can you share with us the files?

**Comment by yiannisgaldadas** [comment] 2017-04-27 12:36
Sure,

Please find attached the .mol2 file (in a txt format since I can't attach a .mol2 file)

Best,
Yiannis
[MLN.txt](https://github.com/Acellera/htmd/files/961567/MLN.txt)

**Comment by j3mdamas** [comment] 2017-04-27 12:47
Thanks. Can you also tell in which version of HTMD you are?

**Comment by yiannisgaldadas** [comment] 2017-04-27 14:12
I am on 1.7.15.

**Comment by yiannisgaldadas** [comment] 2017-04-28 08:58
Is this an issue of the HTMD version that I'm using?

**Comment by j3mdamas** [comment] 2017-04-28 10:19
No, I just wanted the information for completeness

**Comment by j3mdamas** [comment] 2017-08-07 14:08
Hi @yiannisgaldadas,

Sorry for the very late reply.

First of all, we are working on improving the current parameterization tool, and we really appreciate the feedback from the users.

I just ran it with the latest 1.9.4.

Couldn't reproduce your initial feedback, but I had some different:

* Parameterize doesn't like the hydrogen names that are in the file. I changed them all to `H`, similar to the other atoms, and it works out fine
* The QM calculator does not like charge -1. Looking at the structure, the carboxylic contributes with -1, but the nitrogen in the "heptaring", as it is, should be -1, with a total of -2. But if that is an azepine, the structure is wrong and should be corrected accordingly. If you give us the chemical name of the molecule we can advice on that.

With version 1.9.4, and changing the hydrogen names, and putting -2 as charge, I have it running on my machine.

**Comment by yiannisgaldadas** [comment] 2017-08-07 14:44
Dear João,

Thank you very much for your effort and for not giving up on this! It is weird because I changed the hydrogen names to H before sending here and it hadn't worked. In any case, the ligand I am trying to parameterize (MLN8054) is the one co-crystalized in the following protein https://www.rcsb.org/pdb/explore/explore.do?structureId=2wtv.

Thank you once again.

Yiannis

**Comment by j3mdamas** [comment] 2017-08-07 15:30
Looking at https://pubchem.ncbi.nlm.nih.gov/compound/mln8054, with a deprotonated carboxyl, it should be indeed -1, apparently. @cuzzo87, can you confirm?

But at -1, PSI4 complains: 

`RuntimeError: sanity check failed! A multiplicity of 1 with 233 electrons is impossible.`

I don't see a reason for the multiplicity to be different from 1 here, which makes the charge of -1 invalid for such a combination of atoms.

I don't think I can input more than this.

**Comment by yiannisgaldadas** [comment] 2017-08-07 22:23
It's all right, no worries. Could you please though let me know what did you do to get to this stage without any other error?

Thank you once again,
Yiannis

**Comment by j3mdamas** [comment] 2017-08-08 07:39
Hi yannis,

As I described, using htmd 1.9.4, with the compound you provided but
changing the atom names all to H, and giving it a charge of -2, it was
doing the minimization. I didn't follow up on it, as this compound is too
big and I killed the minimization.

João

**Comment by j3mdamas** [comment] 2017-08-08 08:21
Let me revise my last comment: I mistakenly left it running overnight. It was undergoing the first torsion scan, with an ETA of ~100 hours (16 cores machine). You can count the number of torsions and see if that's feasible for you. I was running with the lowest level of theory and smallest basis set.

**Comment by j3mdamas** [comment] 2017-08-10 18:12
Hi @yiannisgaldadas,

What do you think on my feedback?

**Comment by yiannisgaldadas** [comment] 2017-08-11 13:04
Hello @j3mdamas, 
Apologies for not coming back to you earlier. Your feedback was indeed very helpful. I will try to find a way now to make it work with charge -1, but this is irrelevant to HTMD. Thank you once again for your time and effort.

**Comment by j3mdamas** [comment] 2017-08-11 13:05
I would think any other software (Gaussian, etc) will give the same sanity check as PSI4.

I'll close this issue, but you're welcome to come and open a new one, if needed.

Thanks,
João

**Closed by j3mdamas** 2017-08-11 13:05 UTC
Labels: help wanted, Parameterize
