### ISSUE TITLE
Could Not Type Atom C10 With State C.3%4A

### ISSUE THREAD

**Issue by noeliaferruz** [Acellera/htmd#44] opened 2016-06-03 20:58 UTC
I'm moving the parameterization issues here as you told me.
Just got the following error,  I can send the ligand by email. The initial mol2 file has the sybyl atomtype format, not sure if it matters.

```
You are on the latest HTMD version (1.0.26).

 === Parameterise 2016 ===

      (c) Acellera 
        AsymmetricTorsion False
                    Debug False
                   E14FAC 1.0
               Equivalent None
            ExecutionMode LSF
                 FileName mol.mol2
               FixCharges None
             GAUSS_SCRDIR /tmp
                  JobName XXXX04965842
                   MEMORY 8
               MaxTorsion 25
                    Model Nonpolar
             Multiplicity 1
                   NCORES 4
                NetCharge 0
                  Neutral None
                 Torsions []
       w_H_Donor_Acceptor 1.0
                  w_alpha 0.4
                 w_charge 3.0
                  w_thole 0.2
            w_water_E_min 0.4
            w_water_R_min 8.0
                 wd_alpha 0.4
                wd_charge 1.0
                 wd_thole 0.2
           wd_water_E_min 0.4
           wd_water_R_min 8.0

Running step [000] [input]
2016-06-03 16:50:12,199 - parameterise.step - INFO - run(): Step [preoptimize] in dir [/home/ferrun/.htmd/gaamp/XXXX04965842/010-preoptimize]
2016-06-03 16:50:12,201 - parameterise.step - INFO - completed(): Expected outputfile [mol-opt.xyz] not present
2016-06-03 16:50:12,205 - parameterise.step - INFO - run(): Running step [preoptimize]
2016-06-03 16:50:12,205 - parameterise.step - INFO -  Running step [10] 	[preoptimize] 
Running step [010] [preoptimize]
2016-06-03 16:52:27,709 - parameterise.step - INFO - run(): Step [initial_parameters] in dir [/home/ferrun/.htmd/gaamp/XXXX04965842/020-initial_parameters]
2016-06-03 16:52:27,714 - parameterise.step - INFO - completed(): Expected outputfile [mol.rtf] not present
2016-06-03 16:52:27,719 - parameterise.step - INFO - run(): Running step [initial_parameters]
2016-06-03 16:52:27,720 - parameterise.step - INFO -  Running step [20] 	[initial_parameters] 

Running step [020] [initial_parameters]

 Failed to run parameterisation : 
 Failure in step   : initial_parameters
   Directory       : /home/ferrun/.htmd/gaamp/XXXX04965842/020-initial_parameters
   Return value    : 1
   Output          : 
 -- 
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "r" in Point cloud on VDW surface differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "x" in Point cloud on VDW surface differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "s" in VDW surface in binary STL format suitable for 3D printing differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "c" in VDW surface in binary STL format suitable for 3D printing differs from an earlier registration.
==============================
*** Open Babel Warning  in Init
  Cannot open element.txt defaulting to compiled data.
==============================
*** Open Babel Warning  in Init
  Cannot open bondtyp.txt defaulting to compiled data.
==============================
*** Open Babel Warning  in Init
  Cannot open aromatic.txt defaulting to compiled data.
==============================
*** Open Babel Warning  in Init
  Cannot open atomtyp.txt defaulting to compiled data.
1 molecule converted
4 errors 4 warnings 18 audit log messages 
Could Not Type Atom C10 With State C.3%4A at /path/to/acellera/current/python/lib/python3.5/site-packages/parameterise/share/match/bin/../MATCH//lib/MATCHer.pm line 158

```

**Comment by j3mdamas** [comment] 2016-06-06 16:04
As a note: in parameteriZe it happens the same (which not a question of the old package)

**Comment by j3mdamas** [comment] 2016-06-06 16:31
@mj-harvey, I identified that the problem is with the match script that identifies the atom types from the pdb file. If seems like it cannot deal very well with four-carbon-ringed structures (example: squaramide): it knows it is a `C.3%4A`, but then it cannot Type it. The problem is on the TypeAtoms routine inside the AtomTyper perl module that I guess comes from MATCH. Are we even supposed to modify it?

Maybe we should find a future alternative to it. I'm gonna schedule a meeting with you for when you come back.

**Comment by mj-harvey** [comment] 2016-06-07 11:09
In your judgement is this a bug in Match or an inadequacy in the cgenff matching ruleset?

**Comment by j3mdamas** [comment] 2016-06-07 11:56
I don't know. The match has a exception to catch this error, so I would guess it's the ruleset, but this is a very wild guess. I'd need more time to understand how it works.

**Comment by mj-harvey** [comment] 2016-07-12 13:01
Worksaround: The next version of parameterise will let you start from your own parameters (Eg from paramchem) rather than always insisting on MAtching itself. Actually typing this correctly ourselves for cgen 2b6 is more difficult.

**Comment by mj-harvey** [comment] 2016-09-08 00:02
Closing this as no progress is going to be made in our code.

**Closed by mj-harvey** 2016-09-08 00:02 UTC
Labels: bug:high, Parameterize
