### ISSUE TITLE
Assistance in performing an MSM analysis for ligand binding

### ISSUE THREAD

**Issue by jdmadura** [Acellera/htmd#90] opened 2016-07-27 20:09 UTC
We are performing an MSM ligand binding analysis. There are a few questions in the notebook on some of the commands and interpretation. (1) How to convert from ns to frames. We used the assumption of 10 frames per nanosecond. (2) In the TimeScale plot should we be selecting 5 clusters? (3) From the clusters we obtain none of them contain the bound ligand complex. However, when using a smaller set of data we have clusters with the ligand bound. The ipython notebook is attached.

[MSM.ipynb.gz](https://github.com/Acellera/htmd/files/387044/MSM.ipynb.gz)

**Comment by j3mdamas** [comment] 2016-07-27 21:56
So, the (1) I have answered you before.

(2) I would say these are not even well converged. See more on (3)

(3) So, this is an easy (but long) answer. Look at your `data.plotTrajSizes` output. You have ~ 5 trajectories of 6000 frames (600 ns, assuming 0.1 ns timestep), ~ 7 trajectories of ~ 200 frames (20 ns, a very rough approximation based on the plot), and the rest (51) of ~ 100 frames (10 ns, again an estimate based on the plot). I am not sure of the reason for this, I leave that to you, but when you follow by doing `data.dropTraj`, you're basically throwing out of the 12 longer trajectories (more relevant, those ~ 5 very long ones) and keeping only 51 short trajectories (`dropTraj` does not drop the shorter ones, it drops the statistically less common). If you see the output of that command, it gives a list of numbers that should correspond to the longer trajectories that are being thrown away (in the `plotTrajSizes`, the trajectories are plotted ordered by size, so the numbers do not relate). All this explains the lack of sampling that you may need for (2) and reason why a smaller set of data shows clusters with ligand bound (probably using the longer trajectories).

Word of advice: be careful when putting filtered trajectories inside directories with the unfiltered ones.

For me, the issue is solved and the questions are answered, so I am going to close it.

Feel free to comment if you still have any doubts regarding this.

Best,
João

**Closed by j3mdamas** 2016-07-27 21:56 UTC

**Comment by jdmadura** [comment] 2016-07-27 22:02
Dear João, Thank-you for your comments.  I was aware of the simulation lengths in data and we are in the process of correcting them.  Your comments are very helpful and we will try the process once we have longer trajectories.  Best Regards,  Jeffry
