### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/htmd#296] opened 2017-04-04 12:01 UTC
To install I have followed the step:
1) installing conda
2) installing conda version 3.5. (Necessary to use the newer version of nglviewer)
3) conda clean
4) installing htmd by using conda

The error is:
```
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id

ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'acellera::nglview-0.6.2.2-py35_0'.
LinkError: post-link script failed for package acellera::nglview-0.6.2.2-py35_0
running your command again with `-v` will provide additional information
location of failed script: /data-local/alberto/miniconda3/bin/.nglview-post-link.sh
==> script messages <==
<None>


Attempting to roll back.



LinkError: post-link script failed for package acellera::nglview-0.6.2.2-py35_0
running your command again with `-v` will provide additional information
location of failed script: /data-local/alberto/miniconda3/bin/.nglview-post-link.sh
==> script messages <==
<None>
```

**Comment by j3mdamas** [comment] 2017-04-04 12:10
have you ever seen something like this @hainm?

**Comment by hainm** [comment] 2017-04-04 12:23
Try 

conda upgrade conda 

I've seen that with another package and likely a conda bug.

**Comment by j3mdamas** [comment] 2017-04-04 12:32
I am on `4.3.16`, which is the latest, I think, and that's the one causing problems. I also reproduce this issue from Alberto.

**Comment by stefdoerr** [comment] 2017-04-04 12:36
I'm curious though as to why it's pulling 0.6.2.2 
Joao we might need to make a new htmd release because the latest one on acellera is 0.6.2.3 taken from omnia which had a python 3.6 build

@hainm any reason why you don't make 3.6 versions? https://anaconda.org/bioconda/nglview/files It forces us to use the older one from omnia which does

**Comment by j3mdamas** [comment] 2017-04-04 12:57
OK, I am going to make a new HTMD release, with the newest nglview. Let's see how it goes.

Pinning conda to an older conda version (4.3.11) did not work.

**Comment by hainm** [comment] 2017-04-04 12:58
There no python 3.6 yet on bioconda channel

**Comment by hainm** [comment] 2017-04-04 13:15
Side note: IMO, your package should not list nglview or other add-ons as dependence since you don't have control how they are built/delivered. Ideally you should pack all in a single tar file and distribute it (if the license permits that).

**Comment by j3mdamas** [comment] 2017-04-04 13:17
@hainm doesn't that defeat the purpose of conda? :)

I'm releasing 1.7.15, which will have 0.6.2.4 instead of 0.6.2.2.

**Comment by hainm** [comment] 2017-04-04 13:25
You are making assumption that conda is reliable :p

**Comment by j3mdamas** [comment] 2017-04-04 13:29
You have a great point, but we're trying to work with it :) For good and bad

**Comment by j3mdamas** [comment] 2017-04-04 14:20
It's fixed on 1.7.15

@hainm i'm getting this: https://github.com/jupyter-widgets/ipywidgets/issues/662#issuecomment-233708019 as you did in the past with 0.6.2.4. Anything we could do here?

**Closed by j3mdamas** 2017-04-04 14:20 UTC
Labels: bug:medium

**Comment by hainm** [comment] 2017-04-04 14:26
no, it's ipywidgets stuff https://github.com/jupyter-widgets/ipywidgets/issues/1211

**Comment by j3mdamas** [comment] 2017-04-04 14:27
Thanks, let's wait for the next ipywidgets version then.

Thanks a lot for your help, @hainm!
