### ISSUE TITLE
VMD-style select doesn't work when resname is all-digits

### ISSUE THREAD

**Issue by lyu18** [Acellera/htmd#712] opened 2018-06-11 19:13 UTC
Hello,

I found the VMD-style select won't work when seleting residues whose `resname` are all digits (i.e. no Roman character.)

Example:

PDB entry `3udh` has a small molecule ligand whose `resname` is `091`. Say I want to see remove everything except this ligand,

```python
from htmd.molecule.molecule import Molecule
mol = Molecule('3udh')
mol.filter(sel='resname 091')
```

This returns:

```
2018-06-11 14:02:19,552 - htmd.molecule.molecule - INFO - Removed 3464 atoms. 0 atoms remaining in the molecule.
```

*Everything is removed,* i.e. nothing is selected.

However, I know the `resid` for this ligand is `501`, and it works well when selecting it with `resid`:

```python
mol = Molecule('3udh')
mol.filter(sel='resid 501')
```

```
2018-06-11 14:08:40,086 - htmd.molecule.molecule - INFO - Removed 3450 atoms. 14 atoms remaining in the molecule.
```

it also works well for ligands whose `resname` are not all-digits. For example, for another ligand in this PDB entry whose name is `EDO`:

```python
mol = Molecule('3udh')
mol.filter(sel='resname EDO')
```

```
2018-06-11 14:10:03,715 - htmd.molecule.molecule - INFO - Removed 3440 atoms. 24 atoms remaining in the molecule.
```

**Comment by stefdoerr** [comment] 2018-06-11 20:33
Hmmmm that's curious. Could you tell me what `mol.resname.dtype` gives?

**Comment by lyu18** [comment] 2018-06-11 23:51
Here it is:

```python
from htmd.molecule.molecule import Molecule
mol = Molecule('3udh')
print(mol.resname.dtype)
```

```
object
```

**Comment by stefdoerr** [comment] 2018-06-12 20:58
Yes I just checked. Seems like the issue is with numerical resnames starting with 0. The pandas reader cuts off the  zeros because it tries to cast it to integer. I'll try to see what we can do as this coincides with another issue with our PDB reader so I need to see if it's better to fix it or ditch pandas and write my own parser.

**Comment by lyu18** [comment] 2018-06-13 03:08
That makes sense. Thanks Stefan.

**Comment by stefdoerr** [comment] 2018-06-13 09:06
I see that pandas finally allows dtypes for read_fwf. So it should be trivial to do now! I'll give it a try. I'll keep this issue open till it's fixed if you don't mind :)

**Comment by stefdoerr** [comment] 2018-06-13 09:28
Actually I just tested it in VMD and it doesn't work either. So I think I'll close it after all since we are trying to keep compatibility with VMD atomselect. I guess the suggestion is to not use just numbers in resnames.

**Closed by stefdoerr** 2018-06-13 09:28 UTC

**Comment by j3mdamas** [comment] 2018-06-13 10:11
Dear @lyu18,

The "correct" VMD selection for what you want to do is: `mol.filter(sel='resname "091"')`

I hope this helps and we keep the ticket closed has we are keeping the VMD selection patterns and will probably not change them.

**Comment by stefdoerr** [comment] 2018-06-13 11:06
Joao is right but we are still cutting off the initial zeros. I'm making a
PR which fixes that. Then the selection by Joao should work

**Comment by j3mdamas** [comment] 2018-06-13 11:09
Stefan , I just tried and it worked. Unless your new PR cuts the zeros.

**Comment by stefdoerr** [comment] 2018-06-13 11:18
No I'm actually on master and it doesn't work:
```python
In [5]: mol = Molecule('/home/stefan/test.pdb')
2018-06-13 13:17:31,941 - htmd.molecule.readers - WARNING - Non-integer values were read from the PDB "serial" field. Dropping PDB values and assigning new ones.
2018-06-13 13:17:31,956 - htmd.molecule.readers - INFO - Bond indexes in PDB file exceed atom indexes. For safety we will discard all bond information.

In [6]: mol.resname
Out[6]: array(['7', '7', '7', '7', '7', '7', '7', '7', '7'], dtype=object)

In [7]: mol.atomselect('resname "007"')
Out[7]: array([False, False, False, False, False, False, False, False, False], dtype=bool)
```
My test file:
```
MODEL        1
HETATM    1  C1  007 A   1      -1.853  14.311  16.658  1.00 19.86      1    C1-  
HETATM    2  C2  007 A   1      -2.107  15.653  16.758  1.00 19.86      1    C1+
HETATM    3  C3  007 A   1      -1.774  16.341  17.932  1.00 19.86      1    C1-
HETATM    4  C4  007 A   1      -1.175  15.662  19.005  1.00 19.86      1    C0
HETATM    5  C5  007 A   1      -0.914  14.295  18.885  1.00 19.86      1    C  
HETATM    6  C6  007 A   1      -1.257  13.634  17.708  1.00 19.86      1    C  
HETATM    7  C   007 A   1      -2.193  13.627  15.496  1.00 19.86      1    C  
HETATM    8  N1  007 A   1      -2.797  14.235  14.491  1.00 19.86      1    N  
HETATM ****  N2  007 A   1      -1.762  12.391  15.309  1.00 19.86      1    N  
CONECT    1    2    6    7
CONECT    2    1    3
CONECT    3    2    4
CONECT    4    3    5
CONECT    5    4    6
CONECT    6    1    5
CONECT    7    1    8    9
CONECT    8    7
CONECT    9    7
ENDMDL
END
```

**Comment by stefdoerr** [comment] 2018-06-13 11:19
@j3mdamas if you have even one non-number resname in your molecule it will work as it will not cast it to integer. So your test was probably not correct

**Comment by j3mdamas** [comment] 2018-06-13 11:48
OK. I was testing the case @lyu18 sent. Your fix seems reasonable, but for what @lyu18 intended to do, my proposal works, hence we can keep this closed.

Using `dtype` argument in `read_fwf` should be sufficient, right?

**Comment by stefdoerr** [comment] 2018-06-13 11:54
yes but selectively for a few fields only. I have written a fix but I'll
wait for the Molecule.read PR to go through first.
